config/routes.rb
Rails.application.routes.draw do
  resources :roll_books

  root 'home#index'

end

app/models/roll_book.rb
class RollBook < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/roll_books_controller.rb
class RollBooksController < ApplicationController
  before_action :set_roll_book, only: [:show, :edit, :update, :destroy]

  # GET /roll_books
  # GET /roll_books.json
  def index
    @roll_books = RollBook.all
  end

  # GET /roll_books/1
  # GET /roll_books/1.json
  def show
  end

  # GET /roll_books/new
  def new
    @roll_book = RollBook.new
  end

  # GET /roll_books/1/edit
  def edit
  end

  # POST /roll_books
  # POST /roll_books.json
  def create
    @roll_book = RollBook.new(roll_book_params)

    respond_to do |format|
      if @roll_book.save
        format.html { redirect_to @roll_book, notice: 'Roll book was successfully created.' }
        format.json { render :show, status: :created, location: @roll_book }
      else
        format.html { render :new }
        format.json { render json: @roll_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roll_books/1
  # PATCH/PUT /roll_books/1.json
  def update
    respond_to do |format|
      if @roll_book.update(roll_book_params)
        format.html { redirect_to @roll_book, notice: 'Roll book was successfully updated.' }
        format.json { render :show, status: :ok, location: @roll_book }
      else
        format.html { render :edit }
        format.json { render json: @roll_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roll_books/1
  # DELETE /roll_books/1.json
  def destroy
    @roll_book.destroy
    respond_to do |format|
      format.html { redirect_to roll_books_url, notice: 'Roll book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roll_book
      @roll_book = RollBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roll_book_params
      params.require(:roll_book).permit(:Lecture_Hour, :Student_Id_Number, :Name, :Notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roll_books_helper.rb
module RollBooksHelper
end

app/views/home/index.html.erb
<h2>Home Page for Pair Collaboration<h2>
    <p>
      Text.
    <p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnpitDay3Pair</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/roll_books/_form.html.erb
<%= form_for(@roll_book) do |f| %>
  <% if @roll_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roll_book.errors.count, "error") %> prohibited this roll_book from being saved:</h2>

      <ul>
      <% @roll_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Lecture_Hour %><br>
    <%= f.text_field :Lecture_Hour %>
  </div>
  <div class="field">
    <%= f.label :Student_Id_Number %><br>
    <%= f.text_field :Student_Id_Number %>
  </div>
  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Notes %><br>
    <%= f.text_area :Notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roll_books/edit.html.erb
<h1>Editing roll_book</h1>

<%= render 'form' %>

<%= link_to 'Show', @roll_book %> |
<%= link_to 'Back', roll_books_path %>

app/views/roll_books/index.html.erb
<h1>Listing roll_books</h1>

<table>
  <thead>
    <tr>
      <th>Lecture hour</th>
      <th>Student id number</th>
      <th>Name</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roll_books.each do |roll_book| %>
      <tr>
        <td><%= roll_book.Lecture_Hour %></td>
        <td><%= roll_book.Student_Id_Number %></td>
        <td><%= roll_book.Name %></td>
        <td><%= roll_book.Notes %></td>
        <td><%= link_to 'Show', roll_book %></td>
        <td><%= link_to 'Edit', edit_roll_book_path(roll_book) %></td>
        <td><%= link_to 'Destroy', roll_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roll book', new_roll_book_path %>

app/views/roll_books/new.html.erb
<h1>New roll_book</h1>

<%= render 'form' %>

<%= link_to 'Back', roll_books_path %>

app/views/roll_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lecture hour:</strong>
  <%= @roll_book.Lecture_Hour %>
</p>

<p>
  <strong>Student id number:</strong>
  <%= @roll_book.Student_Id_Number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @roll_book.Name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @roll_book.Notes %>
</p>

<%= link_to 'Edit', edit_roll_book_path(@roll_book) %> |
<%= link_to 'Back', roll_books_path %>